### ISSUE TITLE
...was not published because no valid module was found with that path

### ISSUE THREAD

**Issue by jackbond** [PowerShell/PowerShellGet#405]
I ran the following...

dotnet new psmodule

and then attempted to publish the output to my companies NuGet, and got the "no valid module" message. I've run commands like New-ModuleManifest, but no luck.

Is there a COMPLETE walkthrough of how to publish a PowerShell module that isn't filled with outdated information because it's ten years old? Seriously guys, a walkthrough should be pinned to the top of this page, https://blogs.msdn.microsoft.com/powershell/ 

Finally, I'm sure it has been mentioned, but packaging a powershell module should be as integrated and effortless as packaging a NuGet package.

**Comment by alerickson** [comment]
To create a new module you can use the [New-ModuleManifest](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/new-modulemanifest?view=powershell-6) cmdlet.

You can use [Test-ModuleManifest](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/test-modulemanifest?view=powershell-6) to verify contents of the module manifest. 

And to publish, [Publish-Module](https://docs.microsoft.com/en-us/powershell/module/powershellget/publish-module?view=powershell-6).

There are descriptive examples in each doc that should help.

**Comment by jackbond** [comment]
Did all that. Am I not providing enough data to New-ModuleManifest? Thanks for the help!

![image](https://user-images.githubusercontent.com/2799232/51431152-c9436080-1bd9-11e9-9470-ff28fb95eedc.png)

**Comment by jackbond** [comment]
Not sure if it matters, but we're using PowerShellStandard.Library version 5.1.0. And it looks like Powershell itself is fine with the binary...

![image](https://user-images.githubusercontent.com/2799232/51431232-d6148400-1bda-11e9-93e0-ddd12505d875.png)

**Comment by kilasuit** [comment]
This is likely due to Publish-Module needing to look for a folder with the same name as the module you are looking to publish.

Can you create a new folder called `Lazlo.PowerShell.Operations` and move all the files thats under the netstandard2 folder and put them into this new folder?

Then once you do that you should be able to publish by running Publish-module to that `Lazlo.PowerShell.Operations` folder

**Comment by alerickson** [comment]
Yes, you do need to have the the module manifest in a directory with the same name.  The module manifest also needs an author and a description (which you'll need to provide) to be be published.

**Comment by jackbond** [comment]
I eventually discovered that author and description were required when I ran

Publish-Module -Name

instead of

Publish-Module -Path

which gave me better error messages. What really is truly awesome is if author and description are REQUIRED, who the f**k decided to make them f******g optional. And yes, I feel entitled to drop the F bomb because there are EIGHT HOURS OF MY LIFE I'LL NEVER GET BACK because someone decided to put a junior developer, who doesn't understand the difference between REQUIRED AND OPTIONAL, in charge of coding a project where understanding that distinction ought to be a prerequisite.

**Comment by kilasuit** [comment]
@jackbond this is because other systems - like file system based repositories as opposed to the PowerShell Gallery, do not require a them whereas some providers do require them.


This module does need work doing to improve things like this however I have to ask did you run `Get-Help Publish-Module -Examples` at all ?


Though that said I will raise a new issue to add additional help content to the functions in the modules,

**Comment by alerickson** [comment]
You receive an error an error that author and description is required with both Publish-Module -Name and Publish-Module -Path.
